# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/blogs
spring.datasource.username=admin
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JWT
jwt.secret-key=28d890247899e122b82e6e42ae54f5e3d967150e62b124da851ddf423163b953

aws.region=eu-central-1
aws.accessKey=test
aws.secretKey=test
aws.endpoint=http://localhost:4566
aws.s3.base-url=http://localhost:4566/blogs-app
aws.s3.bucketName=blogs-app

logging.cloudwatch.enabled=false
logging.cloudwatch.log-group=blogs-app-log-group

spring.config.import=optional:file:.env

# Actuator
management.endpoints.web.exposure.include=health,metrics,flyway
management.endpoint.health.show-details=always

# OpenSearch
opensearch.host=http://localhost
opensearch.port=9200
opensearch.username=${OPENSEARCH_USERNAME}
opensearch.password=${OPENSEARCH_PASSWORD}
opensearch.ssl.verification-mode=none

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
