# PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JWT
jwt.secret-key=${JWT_SECRET_KEY}

aws.region=${AWS_REGION}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}
aws.s3.base-url=${AWS_S3_BASE_URL:}