# Application Name
spring.application.name=blogs.app

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Location of migration scripts (default)
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

# Hikari
spring.datasource.hikari.connection-timeout=30000

# JWT
jwt.access-token-expiration=30d
jwt.refresh-token-expiration=30d

# Server
server.port=8080

# Scheduled Tasks
revoked-token-cleaner.cron=0 0 * * * *

# File Upload
spring.servlet.multipart.enabled=true
spring.jpa.open-in-view=false